/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module timer_9 (
    input clk,
    input rst,
    output reg out
  );
  
  
  
  wire [8-1:0] M_ctr_value;
  counter_20 ctr (
    .clk(clk),
    .rst(rst),
    .value(M_ctr_value)
  );
  reg M_result_d, M_result_q = 1'h0;
  
  always @* begin
    M_result_d = M_result_q;
    
    out = M_result_q;
    if (M_ctr_value[7+0-:1] == 1'h1) begin
      M_result_d = 1'h1;
    end else begin
      M_result_d = 1'h0;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_result_q <= 1'h0;
    end else begin
      M_result_q <= M_result_d;
    end
  end
  
endmodule
